<?php

// Declare Variables 
         $hostname='localhost';
	 $username='root';
	 $password='';
	 $databasename='diavatly_DSCB';
         $php ="php";
	 $java="java";
         $css="css";
         $html="html";
         $upload="upload";
// Connect to MySQL

$link =mysql_connect($hostname,$username,$password) or die("Can't connect to server");
// Create DataBase
$dat = "create database if not exists $databasename";
mysql_query($dat) or die(mysql_error());

// Using Database
		
mysql_select_db($databasename,$link) or die("Can't select database");

// Create Table detail 
$sql = " CREATE TABLE if not exists resume
        (
	stt int NOT NULL AUTO_INCREMENT, 
	PRIMARY KEY(stt),
        danhso   int(30)  NOT NULL ,
        image   char(80)  NOT NULL ,
        imagebc1   char(80)  NOT NULL ,
        imagebc2   char(80)  NOT NULL ,
        imagebc3   char(80)  NOT NULL ,
	hoten varchar(60) NOT NULL ,
	gioitinh char(10)  NOT NULL ,
	hotenkhac varchar(60) NOT NULL, 
	ngaysinh int(10) NOT NULL ,
        thangsinh int(10) NOT NULL,
	namsinh  int(10) NOT NULL,
	noisinh  char(50) NOT NULL,
	qsonha varchar(50) NOT NULL ,
	qduongpho varchar(100) NOT NULL ,
	qphuong varchar(50) NOT NULL ,
	qhuyenquan varchar(50) NOT NULL ,
	qtinhtp varchar(80) NOT NULL ,
	dsonha varchar(50) NOT NULL ,
	dduongpho varchar(100) NOT NULL ,
	dphuong varchar(50) NOT NULL ,
	dhuyenquan varchar(50) NOT NULL ,
	dtinhtp varchar(80) NOT NULL ,
	dantoc  char(50) NOT NULL,
	tongiao char(50) NOT NULL,
	tpgdxt  char(50) NOT NULL,
	ngtd    char(30) NOT NULL, 
	odau   char(100) NOT NULL,
	ngvaodk char(30) NOT NULL ,
	ngvaold char(30) NOT NULL , 
	ngvaodang char(30) NOT NULL,
	ngct char(30) NOT NULL,
	ngvaotc char(30) NOT NULL,
        tochuc  char(50) NOT NULL,
	trinhdovh char(50) NOT NULL,
	hocham char(50) NOT NULL,
	tdcm varchar(100) NOT NULL, 
	chnganh char(50) NOT NULL,
	nhai char(50) NOT NULL,
	nkhac char(50) NOT NULL,
	llctri  char(50) NOT NULL,
	ngoaingu1 char(50) NOT NULL,
	bangcap1 varchar(100) NOT NULL, 
	damthoai1 char(10) NOT NULL,
	docviet1 char(10) NOT NULL,
	ngoaingu2 char(50) NOT NULL,
	bangcap2 varchar(100) NOT NULL, 
	damthoai2 char(10) NOT NULL,
	docviet2 char(10) NOT NULL,
	ngoaingu3 char(50) NOT NULL,
	bangcap3 varchar(100) NOT NULL, 
	damthoai3 char(10) NOT NULL,
	docviet3 char(10) NOT NULL,
        chucdanh char(50) NOT NULL ,
	donvi   char(100) NOT NULL,
        ngcongchuc char(50) NOT NULL,
        maso char(50) NOT NULL,
        hesoluong char(50) NOT NULL,
        thang char(50) NOT NULL,
        nam char(50) NOT NULL,
        sotrcongtac char(100) NOT NULL,
        cvdlln char(50) NOT NULL,
        khenthuong text NOT NULL,
	kyluat text 	NOT NULL,
	suckhoe char(50) NOT NULL,
	cao char(30) NOT NULL,
	cannang char(30) NOT NULL,
	nhommau char(30) NOT NULL,
	cmnd char(30) NOT NULL ,
        ngaycap char(30) NOT NULL ,
        noicap varchar(50) NOT NULL ,
	thuongbinh char(50) NOT NULL,
	gdlietsy char(50) NOT NULL,
	dangvien varchar(10) NOT NULL, 
	ngll char(30) NOT NULL ,
	ncl char(30) NOT NULL ,
	dtcq char(10) NOT NULL ,
        dtnr char(30) NOT NULL ,
	dtdd  char(50) NOT NULL ,
	lanhdao varchar(10) NOT NULL, 
	noilv varchar(30) NOT NULL, 
	nghiviec varchar(10) NOT NULL, 
        tentruongpt1 char(100) NOT NULL,
	tenloppt1 char(50) NOT NULL,
        thoigianhocpt1 char(100) NOT NULL, 
        hinhthuchocpt1 char(50) NOT NULL,
	bangcappt1 char(80) NOT NULL,
        tentruongdh1 char(100) NOT NULL,
	tenlopdh1 char(50) NOT NULL,
        thoigianhocdh1 char(100) NOT NULL, 
        hinhthuchocdh1 char(50) NOT NULL,
	bangcapdh1 char(80) NOT NULL,
        tentruongpt2 char(100) NOT NULL,
	tenloppt2 char(50) NOT NULL,
        thoigianhocpt2 char(100) NOT NULL, 
        hinhthuchocpt2 char(50) NOT NULL,
	bangcappt2 char(80) NOT NULL,
        tentruongdh2 char(100) NOT NULL,
	tenlopdh2 char(50) NOT NULL,
        thoigianhocdh2 char(100) NOT NULL, 
        hinhthuchocdh2 char(50) NOT NULL,
	bangcapdh2 char(80) NOT NULL,
        tentruongpt3 char(100) NOT NULL,
	tenloppt3 char(50) NOT NULL,
        thoigianhocpt3 char(100) NOT NULL, 
        hinhthuchocpt3 char(50) NOT NULL,
	bangcappt3 char(80) NOT NULL,
        tentruongdh3 char(100) NOT NULL,
	tenlopdh3 char(50) NOT NULL,
        thoigianhocdh3 char(100) NOT NULL, 
        hinhthuchocdh3 char(50) NOT NULL,
	bangcapdh3 char(80) NOT NULL,
        tentruongpt4 char(100) NOT NULL,
	tenloppt4 char(50) NOT NULL,
        thoigianhocpt4 char(100) NOT NULL, 
        hinhthuchocpt4 char(50) NOT NULL,
	bangcappt4 char(80) NOT NULL,
        tentruongdh4 char(100) NOT NULL,
	tenlopdh4 char(50) NOT NULL,
        thoigianhocdh4 char(100) NOT NULL , 
        hinhthuchocdh4 char(50) NOT NULL,
	bangcapdh4 char(80) NOT NULL, 
        tentruongpt5 char(100) NOT NULL,
	tenloppt5 char(50) NOT NULL,
        thoigianhocpt5 char(100) NOT NULL, 
        hinhthuchocpt5 char(50) NOT NULL,
	bangcappt5 char(80) NOT NULL,
        tentruongdh5 char(100) NOT NULL,
	tenlopdh5 char(50) NOT NULL,
        thoigianhocdh5 char(100) NOT NULL , 
        hinhthuchocdh5 char(50) NOT NULL,
	bangcapdh5 char(80) NOT NULL, 
        tentruongdt1 char(100) NOT NULL,
	tenlopdt1 char(100) NOT NULL,
        thoigianhocdt1 char(100) NOT NULL , 
        hinhthuchocdt1 char(100) NOT NULL,
	bangcapdt1 char(80) NOT NULL, 
        tentruongdt2 char(100) NOT NULL,
	tenlopdt2 char(100) NOT NULL,
        thoigianhocdt2 char(100) NOT NULL , 
        hinhthuchocdt2 char(100) NOT NULL,
	bangcapdt2 char(80) NOT NULL, 
        tentruongdt3 char(100) NOT NULL,
	tenlopdt3 char(100) NOT NULL,
        thoigianhocdt3 char(100) NOT NULL , 
        hinhthuchocdt3 char(100) NOT NULL,
	bangcapdt3 char(80) NOT NULL, 
        tentruongdt4 char(100) NOT NULL,
	tenlopdt4 char(100) NOT NULL,
        thoigianhocdt4 char(100) NOT NULL , 
        hinhthuchocdt4 char(100) NOT NULL,
	bangcapdt4 char(80) NOT NULL, 
        tentruongdt5 char(100) NOT NULL,
	tenlopdt5 char(100) NOT NULL,
        thoigianhocdt5 char(100) NOT NULL , 
        hinhthuchocdt5 char(100) NOT NULL,
	bangcapdt5 char(80) NOT NULL, 
        tentruongdt6 char(100) NOT NULL,
	tenlopdt6 char(100) NOT NULL,
        thoigianhocdt6 char(100) NOT NULL , 
        hinhthuchocdt6 char(100) NOT NULL,
	bangcapdt6 char(80) NOT NULL, 
        tentruongdt7 char(100) NOT NULL,
	tenlopdt7 char(100) NOT NULL,
        thoigianhocdt7 char(100) NOT NULL , 
        hinhthuchocdt7 char(100) NOT NULL,
	bangcapdt7 char(80) NOT NULL, 
        tentruongdt8 char(100) NOT NULL,
	tenlopdt8 char(100) NOT NULL,
        thoigianhocdt8 char(100) NOT NULL , 
        hinhthuchocdt8 char(100) NOT NULL,
	bangcapdt8 char(80) NOT NULL, 
        tentruongdt9 char(100) NOT NULL,
	tenlopdt9 char(100) NOT NULL,
        thoigianhocdt9 char(100) NOT NULL , 
        hinhthuchocdt9 char(100) NOT NULL,
	bangcapdt9 char(80) NOT NULL, 
        tentruongdt10 char(100) NOT NULL,
	tenlopdt10 char(100) NOT NULL,
        thoigianhocdt10 char(100) NOT NULL , 
        hinhthuchocdt10 char(100) NOT NULL,
	bangcapdt10 char(80) NOT NULL, 
        tentruongdt11 char(100) NOT NULL,
	tenlopdt11 char(100) NOT NULL,
        thoigianhocdt11 char(100) NOT NULL , 
        hinhthuchocdt11 char(100) NOT NULL,
	bangcapdt11 char(80) NOT NULL, 
        tentruongdt12 char(100) NOT NULL,
	tenlopdt12 char(100) NOT NULL,
        thoigianhocdt12 char(100) NOT NULL , 
        hinhthuchocdt12 char(100) NOT NULL,
	bangcapdt12 char(80) NOT NULL, 
        tentruongdt13 char(100) NOT NULL,
	tenlopdt13 char(100) NOT NULL,
        thoigianhocdt13 char(100) NOT NULL , 
        hinhthuchocdt13 char(100) NOT NULL,
	bangcapdt13 char(80) NOT NULL, 
        tentruongdt14 char(100) NOT NULL,
	tenlopdt14 char(100) NOT NULL,
        thoigianhocdt14 char(100) NOT NULL , 
        hinhthuchocdt14 char(100) NOT NULL,
	bangcapdt14 char(80) NOT NULL, 
        tentruongdt15 char(100) NOT NULL,
	tenlopdt15 char(100) NOT NULL,
        thoigianhocdt15 char(100) NOT NULL , 
        hinhthuchocdt15 char(100) NOT NULL,
	bangcapdt15 char(80) NOT NULL, 
        tentruongdt16 char(100) NOT NULL,
	tenlopdt16 char(100) NOT NULL,
        thoigianhocdt16 char(100) NOT NULL , 
        hinhthuchocdt16 char(100) NOT NULL,
	bangcapdt16 char(80) NOT NULL, 
        tentruongdt17 char(100) NOT NULL,
	tenlopdt17 char(100) NOT NULL,
        thoigianhocdt17 char(100) NOT NULL , 
        hinhthuchocdt17 char(100) NOT NULL,
	bangcapdt17 char(80) NOT NULL, 
        tentruongdt18 char(100) NOT NULL,
	tenlopdt18 char(100) NOT NULL,
        thoigianhocdt18 char(100) NOT NULL , 
        hinhthuchocdt18 char(100) NOT NULL,
	bangcapdt18 char(80) NOT NULL, 
        tentruongdt19 char(100) NOT NULL,
	tenlopdt19 char(100) NOT NULL,
        thoigianhocdt19 char(100) NOT NULL , 
        hinhthuchocdt19 char(100) NOT NULL,
	bangcapdt19 char(80) NOT NULL, 
        tentruongdt20 char(100) NOT NULL,
	tenlopdt20 char(100) NOT NULL,
        thoigianhocdt20 char(100) NOT NULL , 
        hinhthuchocdt20 char(100) NOT NULL,
	bangcapdt20 char(80) NOT NULL, 
        ttqtctdatefrom1 char(100) NOT NULL,
        ttqtctdateto1 char(100) NOT NULL,
	ttqtctdonvi1 char(100) NOT NULL,
        ttqtctchucdanh1 char(100) NOT NULL,
        ttqtctdatefrom2 char(100) NOT NULL,
        ttqtctdateto2 char(100) NOT NULL,
	ttqtctdonvi2 char(100) NOT NULL,
        ttqtctchucdanh2 char(100) NOT NULL,
        ttqtctdatefrom3 char(100) NOT NULL,
        ttqtctdateto3 char(100) NOT NULL,
	ttqtctdonvi3 char(100) NOT NULL,
        ttqtctchucdanh3 char(100) NOT NULL,
        ttqtctdatefrom4 char(100) NOT NULL,
        ttqtctdateto4 char(100) NOT NULL,
	ttqtctdonvi4 char(100) NOT NULL,
        ttqtctchucdanh4 char(100) NOT NULL,
        ttqtctdatefrom5 char(100) NOT NULL,
        ttqtctdateto5 char(100) NOT NULL,
	ttqtctdonvi5 char(100) NOT NULL,
	ttqtctchucdanh5 char(100) NOT NULL, 
        ttqtctdatefrom6 char(100) NOT NULL,
        ttqtctdateto6 char(100) NOT NULL,
	ttqtctdonvi6 char(100) NOT NULL,
	ttqtctchucdanh6 char(100) NOT NULL, 
        ttqtctdatefrom7 char(100) NOT NULL,
        ttqtctdateto7 char(100) NOT NULL,
	ttqtctdonvi7 char(100) NOT NULL,
	ttqtctchucdanh7 char(100) NOT NULL, 
        ttqtctdatefrom8 char(100) NOT NULL,
        ttqtctdateto8 char(100) NOT NULL,
	ttqtctdonvi8 char(100) NOT NULL,
	ttqtctchucdanh8 char(100) NOT NULL, 
        ttqtctdatefrom9 char(100) NOT NULL,
        ttqtctdateto9 char(100) NOT NULL,
	ttqtctdonvi9 char(100) NOT NULL,
	ttqtctchucdanh9 char(100) NOT NULL, 
        ttqtctdatefrom10 char(100) NOT NULL,
        ttqtctdateto10 char(100) NOT NULL,
	ttqtctdonvi10 char(100) NOT NULL,
	ttqtctchucdanh10 char(100) NOT NULL, 
        ttqtctdatefrom11 char(100) NOT NULL,
        ttqtctdateto11 char(100) NOT NULL,
	ttqtctdonvi11 char(100) NOT NULL,
	ttqtctchucdanh11 char(100) NOT NULL, 
        ttqtctdatefrom12 char(100) NOT NULL,
        ttqtctdateto12 char(100) NOT NULL,
	ttqtctdonvi12 char(100) NOT NULL,
	ttqtctchucdanh12 char(100) NOT NULL, 
        ttqtctdatefrom13 char(100) NOT NULL,
        ttqtctdateto13 char(100) NOT NULL,
	ttqtctdonvi13 char(100) NOT NULL,
	ttqtctchucdanh13 char(100) NOT NULL, 
        ttqtctdatefrom14 char(100) NOT NULL,
        ttqtctdateto14 char(100) NOT NULL,
	ttqtctdonvi14 char(100) NOT NULL,
	ttqtctchucdanh14 char(100) NOT NULL, 
        ttqtctdatefrom15 char(100) NOT NULL,
        ttqtctdateto15 char(100) NOT NULL,
	ttqtctdonvi15 char(100) NOT NULL,
	ttqtctchucdanh15 char(100) NOT NULL, 
        ttqtctdatefrom16 char(100) NOT NULL,
        ttqtctdateto16 char(100) NOT NULL,
	ttqtctdonvi16 char(100) NOT NULL,
	ttqtctchucdanh16 char(100) NOT NULL, 
	hvtbode char(50) NOT NULL,
	namsinhbode char(30) NOT NULL,
	ngnghiepbode char(100) NOT NULL,
	hvtmede char(50) NOT NULL,
	namsinhmede char(30) NOT NULL,
	ngnghiepmede char(100) NOT NULL,
	hvtboka char(50) NOT NULL,
	namsinhboka char(30) NOT NULL,
	ngnghiepboka char(100) NOT NULL,
	hvtmeka char(50) NOT NULL,
	namsinhmeka char(30) NOT NULL,
	ngnghiepmeka char(100) NOT NULL,
	hvtvo char(50) NOT NULL,
	namsinhvo char(30) NOT NULL,
	ngnghiepvo char(100) NOT NULL,
	hvtcon1 char(50) NOT NULL,
	namsinhcon1 char(30) NOT NULL,
	ngnghiepcon1 char(100) NOT NULL,
	hvtcon2 char(50) NOT NULL,
	namsinhcon2 char(30) NOT NULL,
	ngnghiepcon2 char(100) NOT NULL,
	hvtcon3 char(50) NOT NULL,
	namsinhcon3 char(30) NOT NULL,
	ngnghiepcon3 char(100) NOT NULL,
	hvtcon4 char(50) NOT NULL,
	namsinhcon4 char(30) NOT NULL,
	ngnghiepcon4 char(100) NOT NULL,
	hvtcon5 char(50) NOT NULL,
	namsinhcon5 char(30) NOT NULL,
	ngnghiepcon5 char(100) NOT NULL,
	hvtanhchi1 char(50) NOT NULL,
	namsinhanhchi1 char(30) NOT NULL,
	ngnghiepanhchi1 char(100) NOT NULL,
	hvtanhchi2 char(50) NOT NULL,
	namsinhanhchi2 char(30) NOT NULL,
	ngnghiepanhchi2 char(100) NOT NULL,
	hvtanhchi3 char(50) NOT NULL,
	namsinhanhchi3 char(30) NOT NULL,
	ngnghiepanhchi3 char(100) NOT NULL,
	hvtanhchi4 char(50) NOT NULL,
	namsinhanhchi4 char(30) NOT NULL,
	ngnghiepanhchi4 char(100) NOT NULL,
	hvtanhchi5 char(50) NOT NULL,
	namsinhanhchi5 char(30) NOT NULL,
	ngnghiepanhchi5 char(100) NOT NULL,
	hvtanhchi6 char(50) NOT NULL,
	namsinhanhchi6 char(30) NOT NULL,
	ngnghiepanhchi6 char(100) NOT NULL,
	hvtanhchi7 char(50) NOT NULL,
	namsinhanhchi7 char(30) NOT NULL,
	ngnghiepanhchi7 char(100) NOT NULL,
	hvtanhchi8 char(50) NOT NULL,
	namsinhanhchi8 char(30) NOT NULL,
	ngnghiepanhchi8 char(100) NOT NULL,
	hvtanhchi9 char(50) NOT NULL,
	namsinhanhchi9 char(30) NOT NULL,
	ngnghiepanhchi9 char(100) NOT NULL,
	hvtanhchi10 char(50) NOT NULL,
	namsinhanhchi10 char(30) NOT NULL,
	ngnghiepanhchi10 char(100) NOT NULL,
        hvtbovo char(50) NOT NULL,
	namsinhbovo char(30) NOT NULL,
	ngnghiepbovo char(100) NOT NULL,
        hvtmevo char(50) NOT NULL,
	namsinhmevo char(30) NOT NULL,
	ngnghiepmevo char(100) NOT NULL,
	hvtanhchivo1 char(50) NOT NULL,
	namsinhanhchivo1 char(30) NOT NULL,
	ngnghiepanhchivo1 char(100) NOT NULL,
	hvtanhchivo2 char(50) NOT NULL,
	namsinhanhchivo2 char(30) NOT NULL,
	ngnghiepanhchivo2 char(100) NOT NULL,
	hvtanhchivo3 char(50) NOT NULL,
	namsinhanhchivo3 char(30) NOT NULL,
	ngnghiepanhchivo3 char(100) NOT NULL,
	hvtanhchivo4 char(50) NOT NULL,
	namsinhanhchivo4 char(30) NOT NULL,
	ngnghiepanhchivo4 char(100) NOT NULL,
	hvtanhchivo5 char(50) NOT NULL,
	namsinhanhchivo5 char(30) NOT NULL,
	ngnghiepanhchivo5 char(100) NOT NULL,
	hvtanhchivo6 char(50) NOT NULL,
	namsinhanhchivo6 char(30) NOT NULL,
	ngnghiepanhchivo6 char(100) NOT NULL,
	hvtanhchivo7 char(50) NOT NULL,
	namsinhanhchivo7 char(30) NOT NULL,
	ngnghiepanhchivo7 char(100) NOT NULL,
	hvtanhchivo8 char(50) NOT NULL,
	namsinhanhchivo8 char(30) NOT NULL,
	ngnghiepanhchivo8 char(100) NOT NULL,
	hvtanhchivo9 char(50) NOT NULL,
	namsinhanhchivo9 char(30) NOT NULL,
	ngnghiepanhchivo9 char(100) NOT NULL,
	hvtanhchivo10 char(50) NOT NULL,
	namsinhanhchivo10 char(30) NOT NULL,
	ngnghiepanhchivo10 char(100) NOT NULL,
	ctnndate1 char(100) NOT NULL,
	ctnntennuoc1 char(100) NOT NULL,
	ctnnlydo1 char(100) NOT NULL,
	ctnndate2 char(100) NOT NULL,
	ctnntennuoc2 char(100) NOT NULL,
	ctnnlydo2 char(100) NOT NULL,
	ctnndate3 char(100) NOT NULL,
	ctnntennuoc3 char(100) NOT NULL,
	ctnnlydo3 char(100) NOT NULL,
	ctnndate4 char(100) NOT NULL,
	ctnntennuoc4 char(100) NOT NULL,
	ctnnlydo4 char(100) NOT NULL,
	ctnndate5 char(100) NOT NULL,
	ctnntennuoc5 char(100) NOT NULL,
	ctnnlydo5 char(100) NOT NULL,
	ctnndate6 char(100) NOT NULL,
	ctnntennuoc6 char(100) NOT NULL,
	ctnnlydo6 char(100) NOT NULL,
	ctnndate7 char(100) NOT NULL,
	ctnntennuoc7 char(100) NOT NULL,
	ctnnlydo7 char(100) NOT NULL,
	ctnndate8 char(100) NOT NULL,
	ctnntennuoc8 char(100) NOT NULL,
	ctnnlydo8 char(100) NOT NULL,
	ctnndate9 char(100) NOT NULL,
	ctnntennuoc9 char(100) NOT NULL,
	ctnnlydo9 char(100) NOT NULL,
	ctnndate10 char(100) NOT NULL,
	ctnntennuoc10 char(100) NOT NULL,
	ctnnlydo10 char(100) NOT NULL,
	hcktdate1 char(50) NOT NULL,
        bac1 char(10) NOT NULL,   
	muc1 char(30) NOT NULL,
	heso1 char(30) NOT NULL,
	hcktdate2 char(50) NOT NULL,
        bac2 char(10) NOT NULL,   
	muc2 char(30) NOT NULL,
	heso2 char(30) NOT NULL,
	hcktdate3 char(50) NOT NULL,
        bac3 char(10) NOT NULL,   
	muc3 char(30) NOT NULL,
	heso3 char(30) NOT NULL,
	hcktdate4 char(50) NOT NULL,
        bac4 char(10) NOT NULL,   
	muc4 char(30) NOT NULL,
	heso4 char(30) NOT NULL,
	hcktdate5 char(50) NOT NULL,
        bac5 char(10) NOT NULL,   
	muc5 char(30) NOT NULL,
	heso5 char(30) NOT NULL,
	hcktdate6 char(50) NOT NULL,
        bac6 char(10) NOT NULL,   
	muc6 char(30) NOT NULL,
	heso6 char(30) NOT NULL,
	hcktdate7 char(50) NOT NULL,
        bac7 char(10) NOT NULL,   
	muc7 char(30) NOT NULL,
	heso7 char(30) NOT NULL,
	hcktdate8 char(50) NOT NULL,
        bac8 char(10) NOT NULL,   
	muc8 char(30) NOT NULL,
	heso8 char(30) NOT NULL,
	luong   int NOT NULL ,
	nguonkhac char(30) NOT NULL ,
	nhacap char(50) NOT NULL ,
        dtnhcap char(30) NOT NULL ,
        nhamua char(50) NOT NULL ,
	dtnhmua char(30) NOT NULL ,
        dtdatcap char(50) NOT NULL ,
	dtdatmua  char(50) NOT NULL ,
	datsx char(50) NOT NULL,
        taisan text NOT NULL,   	
	ngayd int NOT NULL ,
        thangm  int NOT NULL,
	namy  int NOT NULL,
	name char(30) NOT NULL, 
	dochai char(30) NOT NULL, 
	hotenkd char(50) NOT NULL,
	chucdanhkd char(50) NOT NULL,
	tenlopdtkd1 char(100) NOT NULL,
	tenlopdtkd2 char(100) NOT NULL,
	tenlopdtkd3 char(100) NOT NULL,
	tenlopdtkd4 char(100) NOT NULL,
	tenlopdtkd5 char(100) NOT NULL,
	tenlopdtkd6 char(100) NOT NULL,
	tenlopdtkd7 char(100) NOT NULL,
	tenlopdtkd8 char(100) NOT NULL,
	tenlopdtkd9 char(100) NOT NULL,
	tenlopdtkd10 char(100) NOT NULL,
	tenlopdtkd11 char(100) NOT NULL,
	tenlopdtkd12 char(100) NOT NULL,
	tenlopdtkd13 char(100) NOT NULL,
	tenlopdtkd14 char(100) NOT NULL,
	tenlopdtkd15 char(100) NOT NULL,
	chnganhkd char(50) NOT NULL,
	nhaikd char(50) NOT NULL,
	nkhackd char(50) NOT NULL,
	level_ds_sum int(30) NOT NULL,
	level_dv_sum int(30) NOT NULL,
	ybackup int(30) NOT NULL,
	mbackup int(30) NOT NULL,
	dbackup int(30) NOT NULL,
	ngvaodvl char(30) NOT NULL ,
	ngvaodv char(30) NOT NULL ,
	sotrcongtackd varchar(100) NOT NULL 
         )";
	

mysql_query($sql,$link) or die(mysql_error());
// English
$sql = " CREATE TABLE if not exists cv_english
        (
	stt int NOT NULL AUTO_INCREMENT, 
	PRIMARY KEY(stt),
        danhso   int(30)  NOT NULL ,
        image   char(80)  NOT NULL ,
	hoten varchar(200) NOT NULL ,
        gioitinh   char(80)  NOT NULL ,
	dateofbirth varchar(200)  NOT NULL,
	noisinh  char(200) NOT NULL,
	address varchar(200) NOT NULL ,
	lanhdao char(20) NOT NULL ,
	cmnd char(30) NOT NULL ,
	dtdd  char(50) NOT NULL ,
	email varchar(80) NOT NULL, 
	nationality char(50) NOT NULL,
        tentruongdh1 varchar(200) NOT NULL,
        thoigianhocdh1 char(200) NOT NULL, 
	bangcapdh1 char(80) NOT NULL,
        tentruongdh2 varchar(200) NOT NULL,
        thoigianhocdh2 char(200) NOT NULL, 
	bangcapdh2 char(80) NOT NULL,
        tentruongdh3 varchar(200)  NOT NULL,
        thoigianhocdh3 char(200) NOT NULL, 
	bangcapdh3 char(80) NOT NULL,
        tentruongdh4 varchar(200)  NOT NULL,
        thoigianhocdh4 char(200) NOT NULL , 
	bangcapdh4 char(80) NOT NULL, 
        tentruongdh5 varchar(200)  NOT NULL,
        thoigianhocdh5 char(200) NOT NULL , 
	bangcapdh5 char(80) NOT NULL, 
        tentruongdt1 varchar(200)  NOT NULL,
        thoigianhocdt1 char(200) NOT NULL , 
	bangcapdt1 char(80) NOT NULL, 
        tentruongdt2 varchar(200)  NOT NULL,
        thoigianhocdt2 char(200) NOT NULL , 
	bangcapdt2 char(80) NOT NULL, 
        tentruongdt3 varchar(200) NOT NULL,
        thoigianhocdt3 char(200) NOT NULL , 
	bangcapdt3 char(80) NOT NULL, 
        tentruongdt4 varchar(200) NOT NULL,
        thoigianhocdt4 char(200) NOT NULL , 
	bangcapdt4 char(80) NOT NULL, 
        tentruongdt5 varchar(200) NOT NULL,
        thoigianhocdt5 char(200) NOT NULL , 
	bangcapdt5 char(80) NOT NULL, 
        tentruongdt6 varchar(200) NOT NULL,
        thoigianhocdt6 char(200) NOT NULL , 
	bangcapdt6 char(80) NOT NULL, 
        tentruongdt7 varchar(200) NOT NULL,
        thoigianhocdt7 char(200) NOT NULL , 
	bangcapdt7 char(80) NOT NULL, 
        tentruongdt8 varchar(200) NOT NULL,
        thoigianhocdt8 char(200) NOT NULL , 
	bangcapdt8 char(80) NOT NULL, 
        tentruongdt9 varchar(200) NOT NULL,
        thoigianhocdt9 char(200) NOT NULL , 
	bangcapdt9 char(80) NOT NULL, 
        tentruongdt10 varchar(200) NOT NULL,
        thoigianhocdt10 char(200) NOT NULL , 
	bangcapdt10 char(80) NOT NULL, 
        tentruongdt11 varchar(200) NOT NULL,
        thoigianhocdt11 char(200) NOT NULL , 
	bangcapdt11 char(80) NOT NULL, 
        tentruongdt12 varchar(200) NOT NULL,
        thoigianhocdt12 char(200) NOT NULL , 
	bangcapdt12 char(80) NOT NULL, 
        tentruongdt13 varchar(200) NOT NULL,
        thoigianhocdt13 char(200) NOT NULL , 
	bangcapdt13 char(80) NOT NULL, 
        tentruongdt14 varchar(200) NOT NULL,
        thoigianhocdt14 char(200) NOT NULL , 
	bangcapdt14 char(80) NOT NULL, 
        tentruongdt15 varchar(200) NOT NULL,
        thoigianhocdt15 char(200) NOT NULL , 
	bangcapdt15 char(80) NOT NULL, 
        tentruongdt16 varchar(200) NOT NULL,
        thoigianhocdt16 char(200) NOT NULL , 
	bangcapdt16 char(80) NOT NULL, 
        tentruongdt17 varchar(200) NOT NULL,
        thoigianhocdt17 char(200) NOT NULL , 
	bangcapdt17 char(80) NOT NULL, 
        tentruongdt18 varchar(200) NOT NULL,
        thoigianhocdt18 char(200) NOT NULL , 
	bangcapdt18 char(80) NOT NULL, 
        tentruongdt19 varchar(200) NOT NULL,
        thoigianhocdt19 char(200) NOT NULL , 
	bangcapdt19 char(80) NOT NULL, 
        tentruongdt20 varchar(200) NOT NULL,
        thoigianhocdt20 char(200) NOT NULL , 
	bangcapdt20 char(80) NOT NULL, 
        ttqtctdate1 char(200) NOT NULL,
	ttqtctdonvi1 varchar(200) NOT NULL,
        ttqtctchucdanh1 varchar(200) NOT NULL,
        ttqtctdate2 char(200) NOT NULL,
	ttqtctdonvi2 varchar(200) NOT NULL,
        ttqtctchucdanh2 varchar(200) NOT NULL,
        ttqtctdate3 char(200) NOT NULL,
	ttqtctdonvi3 varchar(200) NOT NULL,
        ttqtctchucdanh3 varchar(200) NOT NULL,
        ttqtctdate4 char(200) NOT NULL,
	ttqtctdonvi4 varchar(200) NOT NULL,
        ttqtctchucdanh4 varchar(200) NOT NULL,
        ttqtctdate5 char(200) NOT NULL,
	ttqtctdonvi5 varchar(200) NOT NULL,
	ttqtctchucdanh5 varchar(200) NOT NULL, 
        ttqtctdate6 char(200) NOT NULL,
	ttqtctdonvi6 varchar(200) NOT NULL,
	ttqtctchucdanh6 varchar(200) NOT NULL, 
        ttqtctdate7 char(200) NOT NULL,
	ttqtctdonvi7 varchar(200) NOT NULL,
	ttqtctchucdanh7 varchar(200) NOT NULL, 
        ttqtctdate8 char(200) NOT NULL,
	ttqtctdonvi8 varchar(200) NOT NULL,
	ttqtctchucdanh8 varchar(200) NOT NULL, 
        ttqtctdate9 char(200) NOT NULL,
	ttqtctdonvi9 varchar(200) NOT NULL,
	ttqtctchucdanh9 varchar(200) NOT NULL, 
        ttqtctdate10 char(200) NOT NULL,
	ttqtctdonvi10 varchar(200) NOT NULL,
	ttqtctchucdanh10 varchar(200) NOT NULL, 
        ttqtctdate11 char(200) NOT NULL,
	ttqtctdonvi11 varchar(200) NOT NULL,
	ttqtctchucdanh11 varchar(200) NOT NULL, 
        ttqtctdate12 char(200) NOT NULL,
	ttqtctdonvi12 varchar(200) NOT NULL,
	ttqtctchucdanh12 varchar(200) NOT NULL, 
        ttqtctdate13 char(200) NOT NULL,
	ttqtctdonvi13 varchar(200) NOT NULL,
	ttqtctchucdanh13 varchar(200) NOT NULL, 
        ttqtctdate14 char(200) NOT NULL,
	ttqtctdonvi14 varchar(200) NOT NULL,
	ttqtctchucdanh14 varchar(200) NOT NULL, 
        ttqtctdate15 char(200) NOT NULL,
	ttqtctdonvi15 varchar(200) NOT NULL,
	ttqtctchucdanh15 varchar(200) NOT NULL,
        ngay   int(30)  NOT NULL ,
        thang   int(30)  NOT NULL ,
        nam   int(30)  NOT NULL ,
        expertise text NOT NULL,
        ngoaingu char(200) NOT NULL,
        pc char(200) NOT NULL,
        addskill text NOT NULL
         )";
	

mysql_query($sql,$link) or die(mysql_error());
// Create Table resume back up 
$sql = " CREATE TABLE if not exists resumebackup like resume";
mysql_query($sql,$link) or die(mysql_error());

// Create Table users
$sql = " CREATE TABLE if not exists users
        (
	stt int NOT NULL AUTO_INCREMENT, 
	PRIMARY KEY(stt),
        username VARCHAR( 255 ) NOT NULL ,
        password VARCHAR( 255 ) NOT NULL ,
        email VARCHAR( 255 ) NOT NULL
        ) " ;
mysql_query($sql,$link) or die(mysql_error());
// Create Table nghi phep
$sql = " CREATE TABLE if not exists nghiphep
        (
	stt int NOT NULL AUTO_INCREMENT, 
	PRIMARY KEY(stt),
        danhso   int(30)  NOT NULL ,
        nam   int(30)  NOT NULL ,
        tcphep   int(30)  NOT NULL ,
        songnghi   int(30)  NOT NULL ,
        songphep   int(30)  NOT NULL ,
        phepcl   int(30)  NOT NULL ,
	ngaydi char(50) NOT NULL ,
        ngayve char(50) NOT NULL ,
	tauxe  char(50) NOT NULL, 
	noinghi  char(50) NOT NULL, 
	phuongtien  char(50) NOT NULL, 
	moctinh char(50) NOT NULL
        ) " ;
// Create Table gio cong dinh muc
$sql = " CREATE TABLE if not exists chamcong_giocongdm
        (
	stt int NOT NULL AUTO_INCREMENT, 
	PRIMARY KEY(stt),
        year   int(30)  NOT NULL ,
        month   int(30)  NOT NULL ,
        giocongdinhmuc   int(30)  NOT NULL
        ) " ;
mysql_query($sql,$link) or die(mysql_error());
// Create Table baocao
$sql = " CREATE TABLE if not exists baocao
        (
        quy   char(30)  NOT NULL ,
        nam   int(30)  NOT NULL ,
        soluongc   int(30)  NOT NULL ,
        tuoibqc   float  NOT NULL ,
        tuoibqld   float  NOT NULL ,
        tuoibqtbi   float  NOT NULL ,
        tuoibqtb   float  NOT NULL ,
        tuoibqtdh   float  NOT NULL ,
        tuoibqtskh   float  NOT NULL ,
        tuoibqts   float  NOT NULL ,
        tuoibqths   float  NOT NULL ,
        tuoibqdh   float  NOT NULL ,
        tuoibqcd   float  NOT NULL ,
        tuoibqtc   float  NOT NULL ,
        tuoibqnv   float  NOT NULL ,
        tuoibqcn   float  NOT NULL ,
        tuoibqldpt   float  NOT NULL ,
        dangvienn   int(30)  NOT NULL ,
        phunun   int(30)  NOT NULL ,
        dantocn   int(30)  NOT NULL ,
        lanhdaon   int(30)  NOT NULL ,
        dangvienld   int(30)  NOT NULL ,
        phunuld   int(30)  NOT NULL ,
        dantocld   int(30)  NOT NULL ,
        trenbienn   int(30)  NOT NULL ,
        dangvientbi   int(30)  NOT NULL ,
        phunutbi   int(30)  NOT NULL ,
        dantoctbi   int(30)  NOT NULL ,
        trenbon   int(30)  NOT NULL ,
        dangvientb   int(30)  NOT NULL ,
        phunutb   int(30)  NOT NULL ,
        dantoctb   int(30)  NOT NULL ,
        trendh   int(30)  NOT NULL ,
        dangvientdh   int(30)  NOT NULL ,
        phunutdh   int(30)  NOT NULL ,
        dantoctdh   int(30)  NOT NULL ,
        tdcmtskh   int(30)  NOT NULL ,
        dangvientskh   int(30)  NOT NULL ,
        phunutskh   int(30)  NOT NULL ,
        dantoctskh   int(30)  NOT NULL ,
        tdcmts   int(30)  NOT NULL ,
        dangvients   int(30)  NOT NULL ,
        phunuts   int(30)  NOT NULL ,
        dantocts   int(30)  NOT NULL ,
        tdcmths   int(30)  NOT NULL ,
        dangvienths   int(30)  NOT NULL ,
        phunuths   int(30)  NOT NULL ,
        dantocths   int(30)  NOT NULL ,
        tdcmdh   int(30)  NOT NULL ,
        dangviendh   int(30)  NOT NULL ,
        phunudh   int(30)  NOT NULL ,
        dantocdh   int(30)  NOT NULL ,
        tdcmcd   int(30)  NOT NULL ,
        dangviencd   int(30)  NOT NULL ,
        phunucd   int(30)  NOT NULL ,
        dantoccd   int(30)  NOT NULL ,
        tdcmtc   int(30)  NOT NULL ,
        dangvientc   int(30)  NOT NULL ,
        phunutc   int(30)  NOT NULL ,
        dantoctc   int(30)  NOT NULL ,
        tdcmnv   int(30)  NOT NULL ,
        dangviennv   int(30)  NOT NULL ,
        phununv   int(30)  NOT NULL ,
        dantocnv   int(30)  NOT NULL ,
        tdcmcn   int(30)  NOT NULL ,
        dangviencn   int(30)  NOT NULL ,
        phunucn   int(30)  NOT NULL ,
        dantoccn   int(30)  NOT NULL ,
        tdcmldpt   int(30)  NOT NULL ,
        dangvienldpt   int(30)  NOT NULL ,
        phunuldpt   int(30)  NOT NULL ,
        dantocldpt   int(30)  NOT NULL 
        ) " ;
// Create Table users
$sql = " CREATE TABLE if not exists chamcong
        (
	stt int NOT NULL AUTO_INCREMENT, 
	PRIMARY KEY(stt),
	danhso   int(30)  NOT NULL ,
	hoten varchar(60) NOT NULL ,
	month int NOT NULL ,
	year int NOT NULL ,
	chamcong1 varchar(30) NOT NULL,
	chamcong2 varchar(30) NOT NULL,
	chamcong3 varchar(30) NOT NULL,
	chamcong4 varchar(30) NOT NULL,
	chamcong5 varchar(30) NOT NULL,
	chamcong6 varchar(30) NOT NULL,
	chamcong7 varchar(30) NOT NULL,
	chamcong8 varchar(30) NOT NULL,
	chamcong9 varchar(30) NOT NULL,
	chamcong10 varchar(30) NOT NULL,
	chamcong11 varchar(30) NOT NULL,
	chamcong12 varchar(30) NOT NULL,
	chamcong13 varchar(30) NOT NULL,
	chamcong14 varchar(30) NOT NULL,
	chamcong15 varchar(30) NOT NULL,
	chamcong16 varchar(30) NOT NULL,
	chamcong17 varchar(30) NOT NULL,
	chamcong18 varchar(30) NOT NULL,
	chamcong19 varchar(30) NOT NULL,
	chamcong20 varchar(30) NOT NULL,
	chamcong21 varchar(30) NOT NULL,
	chamcong22 varchar(30) NOT NULL,
	chamcong23 varchar(30) NOT NULL,
	chamcong24 varchar(30) NOT NULL,
	chamcong25 varchar(30) NOT NULL,
	chamcong26 varchar(30) NOT NULL,
	chamcong27 varchar(30) NOT NULL,
	chamcong28 varchar(30) NOT NULL,
	chamcong29 varchar(30) NOT NULL,
	chamcong30 varchar(30) NOT NULL,
	chamcong31 varchar(30) NOT NULL,
        ngaycongthucte float NOT NULL ,
        giocongthucte float NOT NULL ,
        giocongthangtruocchuyenthangnay float NOT NULL ,
        giocongthanhtoanthangnay float NOT NULL ,
        giocongvuotmucchuyenthangsau float NOT NULL ,
        ngayconglamviectrenbo float NOT NULL ,
        congbienthangtruoc float NOT NULL ,
        congbienthangnay float NOT NULL ,
        congbiendochai float NOT NULL ,
        lamdemthangtruoc float NOT NULL ,
        lamdemthangnay float NOT NULL ,
        lamthemgio150 float NOT NULL ,
        lamthemgio200 float NOT NULL ,
        ngaylethangtruoc float NOT NULL ,
        ngaylethangnay float NOT NULL ,
        congomthangtruoc float NOT NULL ,
        congomthangnay float NOT NULL ,
        songaynghipheptrongthang float NOT NULL ,
        thoigiandiphep VARCHAR(255) NOT NULL ,
        tongsogiovuotmucthangtruoc float NOT NULL ,
        tongsogiovuotmucthangnay float NOT NULL ,
        giocongdinhmuc float NOT NULL ,
        ngaycongdinhmuc float NOT NULL ,
        ghichu VARCHAR( 255 ) NOT NULL
        ) " ;
mysql_query($sql,$link) or die(mysql_error());

// Close DataBase
mysql_close($link);
echo "Tạo CSDL thành công" ;
include ("formdn.htm") ;
?>
    


